# Generated by Django 2.0.6 on 2018-06-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_id', models.CharField(max_length=30)),
                ('Task_des', models.CharField(max_length=200)),
                ('Task_priority', models.IntegerField(default=1)),
                ('Task_weight', models.IntegerField(default=1)),
                ('Task_dependant', models.CharField(default=None, max_length=30)),
                ('Task_schedule', models.IntegerField(default=1)),
            ],
        ),
    ]
