# Generated by Django 2.0.6 on 2018-06-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskentry',
            name='Task_dependant',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
