# Generated by Django 2.0.6 on 2018-06-27 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task_manager', '0005_auto_20180627_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskentry',
            name='Task_dependant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Task_manager.TaskEntry'),
        ),
    ]
